### PR TITLE
Feature/add-spatial-units

### PR DESCRIPTION
**Pull request by blairlyons**
Added a float spatialUnitFactorMeters field to the TrajectoryInfo block of output data specifying the conversion factor to meters (i.e. for nanometers, spatialUnitFactorMeters = 1e-9). 

Added this data for the supported simulation engines in different ways:
- CytoSim is always in microns, so just hardcoded it into conversion
- PhysiCell units are saved as a user inputted string in the MultiCellDS files, so I'm extracting it and using pint to parse it and get the conversion factor
- ReaDDy doesn't save units information in trajectory files, so it must be provided by the user
- same for custom data, provided by user

## Pull request recommendations:
- [ ] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [ ] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_
- [ ] Provide relevant tests for your feature or bug fix.
- [ ] Provide or update documentation for any feature added by your pull request.

Thanks for contributing!

### CODE REVIEW

**Review by EricJIsaac — APPROVED** [review]

**Review by EricJIsaac — CHANGES_REQUESTED** [review]
The content of of the changes looks good, but it is concerning that the CI is failing. Do you know why it is failing @blairlyons?

**Comment by blairlyons** [comment]
> The content of of the changes looks good, but it is concerning that the CI is failing. Do you know why it is failing @blairlyons?

it's failing to set up miniconda? yeah I don't know how to resolve that. I was hoping I could wait a bit and try again. Everything's passing in my dev environment

**Review by EricJIsaac — APPROVED** [review]

**Comment by blairlyons** [comment]
@JacksonMaxfield do you know what to do about the CI failures? It looks like it's failing to set up conda?

**Comment by JacksonMaxfield** [comment]
> @JacksonMaxfield do you know what to do about the CI failures? It looks like it's failing to set up conda?

Yea. Looks like GitHub changes their action spec but no worries because `setup-miniconda` has already patched. Go through the `.github/workflows` dir and replace anything with `setup-miniconda@v1` with `setup-miniconda@v2`

**Review by toloudis — APPROVED** [review]

**Pull request merged**
